version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_exclude:
          regex: 'DO_NOT_MERGE'
  - when: pull_request.*
    validate:
      - do: milestone
        must_include:
          regex: r1
